// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import "context"

// URLUpdater is an autogenerated mock type for the URLUpdater type
type URLUpdater struct {
	mock.Mock
}

// UpdateURL provides a mock function with given fields: ctx, newURL, NewAlias, alias
func (_m *URLUpdater) UpdateURL(ctx context.Context, newURL string, NewAlias string, alias string) (int64, error) {
	ret := _m.Called(ctx, newURL, NewAlias, alias)

	if len(ret) == 0 {
		panic("no return value specified for UpdateURL")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (int64, error)); ok {
		return rf(ctx, newURL, NewAlias, alias)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) int64); ok {
		r0 = rf(ctx, newURL, NewAlias, alias)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, newURL, NewAlias, alias)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewURLUpdater creates a new instance of URLUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLUpdater {
	mock := &URLUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
