
FROM golang:1.25-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /out/url-shortener  ./cmd/url-shortener

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /out/url-shortener /app/url-shortener

COPY migrations /app/migrations

RUN mkdir -p /app/storage \
    && touch /app/.env \

EXPOSE 8082

HEALTHCHECK --interval=30s \
            --timeout=3s \
            --start-period=5s \
            --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:8082/ping || exit 1

ENTRYPOINT ["/app/url-shortener"]

